/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false` (hash: 20acc1e6d35869806c3665bd101a832d)
interface __BaseEnv_Env {
	CF_VERSION_METADATA: WorkerVersionMetadata;
	ASSETS: Fetcher;
	JEV_DAILY_LIMIT: "0";
	JEV_MODEL: "jev-1.13.0";
	ROOMS: DurableObjectNamespace<import("./worker/index").SeaRoom>;
	BUDGET: DurableObjectNamespace<import("./worker/index").DailyBudget>;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./worker/index");
		durableNamespaces: "SeaRoom" | "DailyBudget";
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "JEV_DAILY_LIMIT" | "JEV_MODEL">> {}
}
