import { useState } from 'react';
import { LIMITS, makeBackup, parseBackup, swimLabel, moodLabel, type Creature, type LocalCreature } from '../../shared/model';
import { imageElement } from '../lib/images';
import { messageOf } from '../lib/api';
import { Confirm } from './Confirm';

export function Collection({ creatures, onDelete, onImport, onToggle, onEdit, onFind }: { creatures: LocalCreature[]; onDelete: (id: string) => Promise<void>; onImport: (creatures: Creature[]) => Promise<void>; onToggle: (creature: LocalCreature) => Promise<void>; onEdit: (creature: LocalCreature) => void; onFind: (creature: LocalCreature) => Promise<void> }) {
  const [error, setError] = useState(''); const [notice, setNotice] = useState(''); const [deleting, setDeleting] = useState<LocalCreature | null>(null); const [importing, setImporting] = useState<Creature[] | null>(null); const [busy, setBusy] = useState(false);
  const action = async (operation: () => Promise<void>) => { setBusy(true); setError(''); try { await operation(); } catch (failure) { setDeleting(null); setImporting(null); setError(messageOf(failure)); } finally { setBusy(false); } };
  const exportBackup = () => {
    try { const blob = new Blob([makeBackup(creatures)], { type: 'application/json' }); const url = URL.createObjectURL(blob); const link = document.createElement('a'); link.href = url; link.download = `oekaki-no-umi-${new Date().toISOString().slice(0, 10)}.json`; link.click(); setTimeout(() => URL.revokeObjectURL(url), 10000); setNotice('バックアップのダウンロードを開始しました。保存先をご確認ください。元写真は含みません。'); } catch (failure) { setError(messageOf(failure)); }
  };
  return <main className="page collection-page"><div className="collection-heading"><div><span className="eyebrow">EVERY LITTLE LINE, A MEMORY</span><h1>きみだけの ずかん</h1><p>うまれた日の線も、ずっと そのまま。</p></div><span className="collection-count">{creatures.length}<small>ひきの たからもの</small></span></div>{error && <p className="notice error" role="alert">{error}</p>}{notice && <p className="notice" role="status">{notice}</p>}
    {creatures.length ? <div className="collection-grid">{creatures.map((creature, index) => <article className="creature-card" key={creature.id}><div className="specimen"><span className="specimen-number">NO. {String(index + 1).padStart(2, '0')}</span><img src={creature.image} alt={creature.name || 'ななしのこ'} /><span className="specimen-date">{new Date(creature.createdAt).toLocaleDateString('ja-JP')}</span></div><div className="creature-info"><h2>{creature.name || 'ななしのこ'}</h2><p>{swimLabel[creature.swim]} · {moodLabel[creature.personality.mood]}</p><div className="button-row"><button disabled={busy} className="primary small" onClick={() => void action(() => onFind(creature))}>うみで さがす</button><button disabled={busy} onClick={() => void action(() => onToggle(creature))}>{creature.inSea ? 'ずかんで やすむ' : 'うみへ もどす'}</button></div><div className="card-footer"><button className="text-button" onClick={() => onEdit(creature)} disabled={!creature.source || busy}>{creature.source ? 'きりぬきを なおす' : '元写真なし'}</button><button className="text-button" aria-label={`${creature.name || 'ななしのこ'}を削除`} onClick={() => setDeleting(creature)}>さようなら</button></div></div></article>)}</div> : <div className="empty-state"><img src="/art/odd-mint.svg" alt="" /><h2>さいしょの1ひき、まってるよ。</h2><p>「つくる」から、写真やおためしの絵をつれてきてね。</p></div>}
    <section className="backup-card"><div><h2>たからものを、なくさないために。</h2><p>このずかんは、このブラウザにだけ保存されます。<br />機種変更やブラウザのデータ削除の前にバックアップを。</p><small>最大40匹 / 海には20匹。バックアップは切り抜きだけ（元写真・招待リンクなし）。同じIDは上書きしません。取り込んだ子はずかんでおやすみします。</small></div><div className="backup-buttons"><button onClick={exportBackup} disabled={!creatures.length || busy}>↓ バックアップを 保存</button><label className="button file-button">↑ バックアップを 読みこむ<input type="file" aria-label="バックアップを読みこむ" accept="application/json,.json" disabled={busy} onChange={event => {
      const file = event.target.files?.[0]; event.target.value = ''; if (!file) return;
      void action(async () => { if (file.size > LIMITS.backupBytes) throw new Error('バックアップは10MBまでです。'); const parsed = parseBackup(await file.text()); for (const creature of parsed) await imageElement(creature.image); setImporting(parsed); });
    }} /></label></div></section>
    {deleting && <Confirm title="このこと さようならする？" confirm="この端末から 消す" busy={busy} onCancel={() => setDeleting(null)} onConfirm={() => void action(async () => { await onDelete(deleting.id); setDeleting(null); setNotice('この端末の画像と元写真を削除しました。共有ルームのコピーは別に削除してください。'); })}><img src={deleting.image} className="confirm-creature" alt={deleting.name || '削除するこ'} /><p>この端末の切り抜きと元写真を消します。取り消せません。必要なら先にバックアップしてください。共有ルームのコピーは残ります。</p></Confirm>}
    {importing && <Confirm title="バックアップのこを おむかえする？" confirm="上書きせず 読みこむ" busy={busy} onCancel={() => setImporting(null)} onConfirm={() => void action(async () => { await onImport(importing); setImporting(null); setNotice('ずかんに読みこみました。同じIDの子は上書きせず、そのままです。'); })}><p>{importing.length}匹のデータです。今いる子は消しません。同じIDの子はスキップします。合計40匹を超える場合は変更しません。</p></Confirm>}
  </main>;
}
