import { useEffect, useRef, useState } from 'react';
import QRCode from 'qrcode';
import { isCapability, isId, validateCreature, type LocalCreature } from '../../shared/model';
import { api, messageOf } from '../lib/api';
import { readRoom, sessionKey, storeRoom, useRoom } from '../lib/room-client';
import { Confirm } from './Confirm';
import { Sea } from './Sea';

export function Family({ navigate }: { navigate: (path: string) => void }) {
  const [busy, setBusy] = useState(false); const [error, setError] = useState(''); const [invite, setInvite] = useState('');
  return <main className="page family-page"><div className="page-heading"><span className="eyebrow">A SEA WE MAKE TOGETHER</span><h1>みんなで、ひとつのうみ。</h1><p>リビングの大きな画面に、家族のえが あつまる。<br />はなれていても、同じうみで。</p></div><div className="family-illustration"><div className="screen-art"><img src="/art/fish-coral.svg" alt="家族で作る魚たちのうみ" /><img src="/art/jelly-lilac.svg" alt="" /><img src="/art/odd-mint.svg" alt="" /></div><div className="phone-art"><img src="/art/fish-sun.svg" alt="スマホから魚を送る" /></div><span className="connection-dots">· · ·</span></div><section className="family-start work-card"><h2>家族だけのうみを ひらく</h2><p>PC・タブレット・スマホ、どれでも作れます。<br />招待リンクやQRを、家族にだけわたしてね。</p><button className="primary" disabled={busy} onClick={async () => {
    setBusy(true); setError('');
    try { const result = await api<{ id: string; join: string; owner: string }>('/api/rooms', { method: 'POST' }); storeRoom(result.id, { join: result.join, owner: result.owner }); navigate(`/room/${result.id}`); }
    catch (failure) { setError(messageOf(failure)); } finally { setBusy(false); }
  }}>{busy ? 'うみを ひらいているよ…' : '＋ みんなのうみを つくる'}</button><div className="limits-row"><span>招待だけ</span><span>20ひきまで</span><span>6時間で消える</span><span>ログインなし</span></div><small>共有した切り抜き画像は、一時ルームに最大6時間保存。作成者がいつでも終了・削除できます。元写真は送らず、端末のずかんはそのまま残ります。リンクを知る人は参加できるため、公開SNSには載せないでください。</small><details className="join-details"><summary>招待リンクを はりつけて参加</summary><input aria-label="招待リンク" type="text" value={invite} onChange={event => setInvite(event.target.value)} placeholder="家族からもらったリンク" autoComplete="off" /><button onClick={() => { try { const url = new URL(invite); const id = url.pathname.split('/')[2]; const join = new URLSearchParams(url.hash.slice(1)).get('join'); if (url.origin !== location.origin || !isId(id) || !isCapability(join)) throw new Error('このサイトの招待リンクをはりつけてください。'); storeRoom(id, { join }); setInvite(''); navigate(`/room/${id}`); } catch (failure) { setError(messageOf(failure)); } }}>このうみに はいる</button></details>{error && <p className="notice error" role="alert">{error}</p>}</section></main>;
}
export function FamilyRoom({ id, collection, navigate }: { id: string; collection: LocalCreature[]; navigate: (path: string) => void }) {
  const [keys] = useState(() => readRoom(id)); const room = useRoom(id, keys); const qr = useRef<HTMLCanvasElement>(null);
  const [inviteOpen, setInviteOpen] = useState(false); const [selected, setSelected] = useState(''); const [sharing, setSharing] = useState(false); const [busy, setBusy] = useState(false); const [error, setError] = useState(''); const [notice, setNotice] = useState('');
  const [confirmation, setConfirmation] = useState<'close' | string | null>(null); const [sender, setSender] = useState('みずいろ'); const [findId, setFindId] = useState('');
  const invite = keys ? `${location.origin}/room/${id}#join=${keys.join}` : '';
  useEffect(() => { if (inviteOpen && qr.current && invite) void QRCode.toCanvas(qr.current, invite, { width: 200, margin: 2, color: { dark: '#285e60', light: '#fffefa' } }).catch(() => setError('QRを作れませんでした。リンクを使ってください。')); }, [inviteOpen, invite]);
  if (room.status === 'closed') return <main className="page empty-state"><span className="empty-mark">☾</span><h1>このうみは、おやすみ。</h1><p>共有の画像は消えました。<br />端末のずかんには、ちゃんといるよ。</p><button className="primary" onClick={() => navigate('/family')}>あたらしいうみを つくる</button></main>;
  const chosen = collection.find(creature => creature.id === selected);
  return <main className="page room-page"><div className="room-heading"><div><span className="eyebrow">OUR LITTLE OCEAN</span><h1>みんなのうみ</h1></div><span className={`connection-status ${room.status}`} role="status">{room.status === 'online' ? '● つながっているよ' : room.status === 'connecting' ? '◌ つないでいるよ' : '○ つながっていません'}</span></div>
    {(room.error || error) && <p className="notice error" role="alert">{error || room.error}<button onClick={room.retry}>つなぎなおす</button></p>}
    <Sea creatures={room.creatures} onInteraction={room.send} remoteEvent={room.remoteEvent} findId={findId} fullscreen />
    <div className="room-actions"><button onClick={() => setInviteOpen(current => !current)} disabled={!keys}>▦ 家族を しょうたい</button><span>{room.expiresAt ? `${new Date(room.expiresAt).toLocaleTimeString('ja-JP', { hour: '2-digit', minute: '2-digit' })}まで · 最長6時間` : '招待制のうみ'}</span><button className="text-button" onClick={() => { if (!keys?.owner) sessionStorage.removeItem(sessionKey(id)); navigate('/family'); }}>{keys?.owner ? 'いったん もどる' : 'この端末は ぬける'}</button></div>
    {keys?.owner && <p className="small-note">作成者は「いったん もどる」後も、同じタブで招待リンクから戻れます。タブを閉じると管理権限は失われます。おしまいにするときは「このうみを 終了する」を使ってね。</p>}
    {inviteOpen && <section className="invite-card work-card"><div><h2>このQRを よみとってね</h2><p>招待リンクを知る人だけが参加できます。<br />QR・リンクは家族にだけ。スクショの公開も避けてね。</p><button onClick={async () => { try { await navigator.clipboard.writeText(invite); setNotice('招待リンクをコピーしました。家族だけに渡してください。'); } catch { setNotice('リンク欄を長押ししてコピーしてください。'); } }}>招待リンクを コピー</button><input aria-label="共有する招待リンク" readOnly value={invite} onFocus={event => event.target.select()} /></div><canvas ref={qr} aria-label="招待リンクのQRコード" /></section>}
    <section className="room-share work-card"><div><h2>ずかんのこを つれてくる</h2><p>確認した切り抜きPNGだけを送ります。元写真はこの端末から出ません。</p></div>{collection.length ? <div className="share-controls"><label>わたしの しるし<select aria-label="わたしのしるし" value={sender} onChange={event => setSender(event.target.value)}>{['みずいろ', 'ももいろ', 'きいろ', 'みどり', 'むらさき', 'しろ'].map(value => <option key={value}>{value}</option>)}</select></label><label>つれてくるこ<select aria-label="共有するいきもの" value={selected} onChange={event => setSelected(event.target.value)}><option value="">えらんでね</option>{collection.map((creature, index) => <option key={creature.id} value={creature.id}>{creature.name || `ななしのこ ${index + 1}`}</option>)}</select></label><button className="primary" disabled={!chosen || room.status !== 'online'} onClick={() => setSharing(true)}>このこを つれてくる</button></div> : <p>まだ、ずかんにいません。<button className="text-button" onClick={() => navigate('/create')}>いきものを つくろう →</button></p>}
    </section><div className="shared-list" data-testid="shared-creatures">{room.members.map(creature => <div key={creature.id} className="shared-member" data-ready={creature.ready} data-failed={creature.failed}><span className="member-swatch" data-color={creature.sender} /><strong>{creature.name || 'ななしのこ'}</strong><small>{creature.sender}のこ · {creature.failed ? 'とどかなかったよ · 共有画像は消しました' : creature.ready ? '大画面に とどいたよ' : '大画面の準備を まっているよ（30秒まで）'}</small><button disabled={creature.failed} onClick={() => { setFindId(''); requestAnimationFrame(() => setFindId(creature.id)); room.send({ type: 'call', id: creature.id, x: 0.5, y: 0.4 }); }}>よぶ</button>{keys?.owner && <button className="text-button" onClick={() => setConfirmation(creature.id)}>共有から はずす</button>}</div>)}</div>
    <p className="small-note">作成した画面を開いておくと「大画面に とどいたよ」を確認できます。30秒で届かなければ共有画像を消し、自動では送り直しません。もう一度送るときは、作成者が「共有から はずす」を押してから送ってね。端末のずかんは残ります。</p>
    {notice && <p className="notice" role="status">{notice}</p>}
    {keys?.owner && <button className="text-button danger-text" onClick={() => setConfirmation('close')}>このうみを 終了する</button>}
    {sharing && chosen && <Confirm title="このこを 家族のうみへ？" confirm="切り抜きだけ 送る" busy={busy} onCancel={() => setSharing(false)} onConfirm={async () => { setBusy(true); setError(''); try { const result = await api<{ duplicate?: boolean; failed?: boolean }>(`/api/rooms/${id}/creatures`, { method: 'POST', headers: room.headers, body: JSON.stringify({ creature: validateCreature(chosen), sender }) }); setSharing(false); setNotice(result.failed ? '前の送信は届きませんでした。作成者が「共有から はずす」を押してから、もう一度送ってね。' : result.duplicate ? 'このこは もう同じうみにいます。' : '送りました。作成した画面の画像準備が終わると「とどいたよ」になります。'); } catch (failure) { setError(messageOf(failure)); setSharing(false); } finally { setBusy(false); } }}><img className="confirm-creature" src={chosen.image} alt={chosen.name || '共有する切り抜き'} /><p>この切り抜きPNGと、なまえ・泳ぎ方・せいかく・しるしを送ります。元写真は送りません。<strong>このルームの参加者に表示され、最長6時間で消えます。</strong>端末のずかんは残ります。</p></Confirm>}
    {confirmation && <Confirm title={confirmation === 'close' ? 'みんなのうみを おしまいにする？' : 'このこの 共有コピーを 消す？'} confirm={confirmation === 'close' ? '終了して 共有画像を消す' : '共有コピーを 消す'} busy={busy} onCancel={() => setConfirmation(null)} onConfirm={async () => { setBusy(true); try { await api(`/api/rooms/${id}${confirmation === 'close' ? '' : `/creatures/${confirmation}`}`, { method: 'DELETE', headers: room.headers }); setConfirmation(null); } catch (failure) { setError(messageOf(failure)); setConfirmation(null); } finally { setBusy(false); } }}><p>家族の画面から共有画像が消えます。<br />それぞれの端末のずかん・元写真は消しません。</p></Confirm>}
  </main>;
}
